sudo: required

services:
- docker

language: cpp
dist: xenial
os: linux

git:
  autocrlf: false

addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.bintray.com/igagis/ubuntu xenial main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x379CE192D401AB61'
    update: true
    packages:
    - binfmt-support
    - qemu-user-static
    - myci
  homebrew:
    update: true
    taps:
    - igagis/tap
    packages:
    - myci

matrix:
  include:
    - name: macosx
      os: osx
      compiler: clang
      osx_image: xcode11
    - name: ios
      os: osx
      compiler: clang
      osx_image: xcode11
    - name: android
      language: android
      android:
        components:
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-28
#          - sys-img-armeabi-v7a-android-22
          - extra-android-m2repository
    - name: msys2
      os: windows


env:
  global:
  # Encrypted MYCI_BINTRAY_API_KEY for publishing to bintray.
  - secure: "uRzU7dQwYFqkpARm7a3hQy5iW4jIt7mhllsWGMmngz8/aEksr1X/PxvRaw8maHT2JB/dHRCvj1XKrM8GVs1lzXMfu2sAhYlfkqbd5GHF156evmkuQM5gyIEZqfX2B7/+UqXW6aHLvo4Ctp4A7rwoHrmeOIzz8oS4RpiaRbwgp4Nwx8INvuyEvs4k0g46aMBcNTDdXLAUTSMosI5uW5IzLTgZ8gnK5JQ6QG1CAynkFuF3FEmz6vFofMBnfwovEIWjiBLIn3p/W0bbtMRx37dR+oCkPcM7knf8kZAaeF6/CXUqgDimku2VrkhwLNnC1jxCR5Z6nk044wJdGYYQ8LuQoe9ctWqf7pJK5yvhIf3G0j4ik4q8XhmYUHmW5s0KK9UhV1u248O7ZKs8wZOpq1P17lPTzUBwAGKCklRqtvOptM3XdTQ/RSI1Vvp8v8z27gs8eN356/AQNjx6dgvzJEMPrpJUUgxSa5q/bYcX/wJY3J9bdfP2OOkzoppTneoBdI19KMTzh6p7bU4W/GsOeBqOYR8D6D4ceu0Qpsp7/XOYF7V67SvfdZKomSVcMezcX2BuLjCaEpZNEx+I6jBzmdQFKN+EFYnda0Rd4Ioqxh96DIwN0xI0NfZWvsEZvHcai2lxGWA3W3q5xQqkzlHbx5LQ8G0I7bdBxbzRniH7VOn+qHg="
  # Encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap and cocoapods-repo.
  - secure: "e5sTF/wTHyKZmcF/A5cd7RfLO3g9oeYpXBzgxvG5fTbBn8O/SXUR//qQ62Ij5qtaSK0fm8j6uYL/QG/0PLXMrny639xFKLWnujiSYgr3JclZZhE81DRGbTqopjyAY4T/C6XQKEevLsIplEWXLCqXlLNQrRrD8g3fqaWvE3nL+Cr0Df+MocvuzNh/OxrsBFt1xtVXrHc3VTo8qc0EejWYT8UGscSco874/ZaA4IGURjopITr4BCi6s848hkxVZcZeJYWXs20gXd5qAacMNB/4PvVLXqKcGoU2YABlU46pd4atkFaCgQTsegG+HST2vp3YUZnNi1oiaX8des/fU4V7CQxThEGNbXrfCPZNC11REfB5HKY+DcQeynBDMZwufIRUKOlVkHekEq2LBobfZfg8S2Gm8/ZZJS457jZx5pwZsWxhxkVqwJQwMnNNPmEMCvZqQzEADNJPKhps6juiwip+p1pMIMnr4KwEn6xiYwAfLBhc7/3KWOFCrsIi243kOat//2zIskRAf4EM9rZPRiXg/OS/XN7VyMwizOuHqnXUp61gR4fbWjouwRpCTlfZDnNdb3cE8o54VLcVumnGfTOX8q0xMy0hN5QRqRQ9DlGkQjwnK/DxTbdWxusXAzaGwn5ZmhhZ53B8tN/LdEH+Ep6opasl7bLKtBh99pnLjpDfL7o="
  - MYCI_GIT_USERNAME=igagis
  - PACKAGE_NAME=aumiks
  matrix:
  - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=debian DOCKER_IMAGE=i386/$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker run --name ccc -v $TRAVIS_BUILD_DIR/..:/build -w /build/$(basename $TRAVIS_BUILD_DIR) -it -d $DOCKER_IMAGE bash &&
    if [ "$PACKAGE_TYPE" == "deb" ]; then
      docker exec ccc apt update &&
      docker exec ccc apt install -y dirmngr &&
      docker exec ccc bash -c "echo 'deb http://dl.bintray.com/igagis/$OS $OS_REL main' > /etc/apt/sources.list.d/igagis.list" &&
      docker exec ccc apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
      docker exec ccc apt update &&
      docker exec ccc apt install -y devscripts equivs myci &&
      myci-deb-prepare.sh;
    fi;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    brew install prorab prorab-extra libpapki libaudout;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$MYCI_GIT_USERNAME:$MYCI_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=xcode;
  fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    choco upgrade --no-progress -y msys2 &&
    export msys2="/c/tools/msys64/msys2_shell.cmd -defterm -no-start -msys -here -c" &&
    $msys2 "echo -e '[igagis_msys]\\nSigLevel ^= Optional TrustAll\\nServer ^= https://dl.bintray.com/igagis/msys2/msys' ^>^> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw64]\\nSigLevel ^= Optional TrustAll\\nServer ^= https://dl.bintray.com/igagis/msys2/mingw64' ^>^> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw32]\\nSigLevel ^= Optional TrustAll\\nServer ^= https://dl.bintray.com/igagis/msys2/mingw32' ^>^> /etc/pacman.conf" &&
    $msys2 "pacman -Sy --noconfirm myci mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain";
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] || [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export PACKAGE_VERSION=$(myci-deb-version.sh debian/changelog);
  fi

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc myci-deb-install-build-deps.sh;
  fi
# Accept android SDK licenses and install android tools
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    echo y | sdkmanager "ndk-bundle" &&
    echo y | sdkmanager "cmake;3.6.4111459";
  fi

before_script:
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
    chmod +x XcodeProjAdder &&
    (cd xcode/$PACKAGE_NAME && ../../XcodeProjAdder -XCP $PACKAGE_NAME.xcodeproj -SCSV `echo $(find ../../src -type f -name *.cpp) | sed -E -e 's/ /,/g'`)
  fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "myci-apply-version.sh -v \$^(myci-deb-version.sh debian/changelog^) msys2/PKGBUILD.in";
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc dpkg-buildpackage -us -uc;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    make;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    xcodebuild -workspace xcode/$PACKAGE_NAME.xcworkspace -scheme $PACKAGE_NAME CONFIGURATION_BUILD_DIR=../build -configuration Release &&
    myci-create-zip-package.sh -h src -f xcode/build/lib$PACKAGE_NAME.a///lib/ios -f LICENSE $PACKAGE_NAME-$PACKAGE_VERSION.zip;
  fi
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    myci-apply-version.sh -v $PACKAGE_VERSION android/*.pom.in &&
    myci-apply-version.sh -v $PACKAGE_VERSION android/*.aar.in --filename-only;
  fi
# running MSYS2 script from deployment provider did not work for some reason, so we do it here if the commit is a tagged one.
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "^(cd msys2 ^&^& PKGEXT^='.pkg.tar.xz' makepkg-mingw --syncdeps --noconfirm --skipinteg^)" &&
    if [ ! -z "$TRAVIS_TAG" ]; then
      for f in $(find msys2 -name "mingw-w64-x86_64-$PACKAGE_NAME-*-any.pkg.*"); do
        $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw64 -d igagis_mingw64 $f";
      done &&
      for f in $(find msys2 -name "mingw-w64-i686-$PACKAGE_NAME-*-any.pkg.*"); do
        $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw32 -d igagis_mingw32 $f";
      done;
    fi;
  fi

deploy:
- provider: script
  skip_cleanup: true
  on:
    tags: true
    condition: $PACKAGE_TYPE = deb && -z "$TRAVIS_JOB_NAME"
  script: myci-deploy-debian-bintray.sh -u igagis -r $OS -p $PACKAGE_NAME -c main -d $OS_REL $TRAVIS_BUILD_DIR/../*.deb
- provider: script
  skip_cleanup: true
  script: myci-deploy-maven-bintray.sh -u igagis -r android -d io/github/igagis -p $PACKAGE_NAME -v $PACKAGE_VERSION android/$PACKAGE_NAME-$PACKAGE_VERSION.aar
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = android
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = macosx
- provider: script
  skip_cleanup: true
  script: myci-deploy-cocoapods.sh -r igagis -v $PACKAGE_VERSION -u igagis -b cocoapods -p $PACKAGE_NAME-$PACKAGE_VERSION.zip cocoapods/$PACKAGE_NAME.podspec.in
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = ios

