language: cpp
sudo: required
dist: trusty
osx_image: xcode7.3

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

env:
  global:
  #encrypted HOMEBREW_GITHUB_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "5N3WCLkGAbj50kPLgES80DqqvcZjlIufQoUI8jAsTiktKrC4Qv2s/BJIitnCjUP8dRB/FYlbSpgQXHZHeVxfOs3zREGPzryrkAAGXdARHsGDk3cYLq502NyknMJ+ElIu1my+pfgrccNirBYwATq/w0d6j53r10wb6mFFMwcHlxZQYLLTAPCnK0V2sCT708mV5ZCHgYGpfL/qOS/XjFGVSU2pu9KLypLf/tjpkqKLUsIg9Bx01i6LZ7wNsUleo8ytRzUjy9krJEIAmXHDuWeZZfsp22ylNTHeVWL5wWBQCgrRmNeiZtqTAbSx8y/z95l7GFYPinzoWDCB4THeZX7DjlKe2mmccjZjNFB3ETPsj+v7gAWahRZ1nYII3np2Zo/5ZM7O8vQoPEmwOC9OVZ5fscFCsJ/7UJS1WMR6Hdrp7vkiXguB7VqjDAGp5g8+YEI9OMIpPyqKTjT2lpj+hmN38T9uabZzpVcTvnjauphjqGQbOLZ++BWoUkk38pI+I/f0ZVyJW7hE78+DigjV1TZi2M8UEJK/Y9IkYrNEcvjViD/PuL5b4lB9QeL3mQbFqflR/jbD6gReVR6oTdQSpaCf6edIdEJHfdi/UWrGT1F2CTxpnWHk8ztU/nbtzaI8H/qWblHARXYhCHrdcr+l4kJ7GoQeFA6asAQ88u9Jq5KZUu0="
  - HOMEBREW_GITHUB_USERNAME=igagis

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    echo "deb https://dl.bintray.com/igagis/deb /" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq debhelper prorab doxygen libpapki-dev libaudout-dev;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    rvm use ruby-2.2.1 &&
    pod repo add --silent igagis https://$HOMEBREW_GITHUB_USERNAME:$HOMEBREW_GITHUB_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=ios &&

    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab libpapki libaudout;
  fi


script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    make deb;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    make &&

    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO &&

    if [ -n "$TRAVIS_TAG" ]; then prorab-deploy-cocoapods.sh igagis; else echo "Skip deploying to cocoapods because not a tagged commit!!!"; fi;
  fi

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux && $CC = gcc
  file: travis_bintray.json
  user: igagis
  key:
    secure: "ClAQ9vIUw9heaB2dkYElOp0zzo8gAwOotWLv4HECbo6YwuRHhNnmWPvtMvuxz7SFupnhuAlmaRILFd7Wc50hGUvCHSW/eEerhVgUyjT0lyvVR+gAgnbOls5ORAgVkYr2Fz/TfsWSK9AKLG/qXL1YsF4vkDyDFRTkz9ZcoEo+WYMGNlj/g7b1rcHjSBOLfo3d6SGC7NL0w6kBH1PB+R3fH2yQxx6G8mOoJMowKK9FsosR/QnosS6CbI2d6PmHyJ5RRdOcPotBUCmK4tL+06zsGmxgoig8qhYr5YU0zRBillOTzDzqPsMC7GCxkJP3eTbbq8biOFxetY3IUrr25RsISjSaNFjzSxNB5yZtvEYClXKwqAOlUDsW63rpO2zb2iBDLPc5J3p1qtaMjFT8DMqtjfDufXEQuoWCuEc8CgMdln//kizGQC3F14Fr/fw7pWBRIxToNi42gSSzJnlKqkm3jvmS9lOWqBlMnR1DJEu4MqUajcCdLUDpHu/eqy8xMT2I3usRNzCcQRH86xngFPsT6px+UxVSLJ+i7i11SEDlWlpEzNTlrlYGtpGNvauAk/mFAaHjA7J0Njkql5C5Mx8Gc+OtUqT3BuuRuyL6EropfNluHfb3HQPE+Jax8Td1CpOO+H9T/+lTFsPxsnZGlEHKA5OwsC+cj1w4qhZSD+P15nU="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-homebrew.sh igagis/tap
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx && $CC = clang
