project 'tests.xcodeproj'

source 'https://github.com/igagis/cocoapods-repo.git'

target "tests" do
	pod 'libutki', '>= 1.0.21'
	pod 'libaudout', '>= 0.3.2'
	pod 'libpapki', '>= 1.0.9'
	pod 'libnitki', '>= 1.0.6'
end
